import React,{ useEffect, useState } from 'react';
import Head from 'next/head'
import Layout from '@/components/Layout'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Header } from '@/components/Header';
import HomeComponent from '@/components/HomeComponent';
import config from '../config';

export default function Home({cartTrace, setCarttrace, keywords, setKeywords}) {
  const baseUrl = config.bUrl;
  const [cartTotal, setCartTotal] = useState(0)
  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(true)

  
  const filterSearch = () => {

    if(keywords == "")
    {
      getProducts()
    }else{
      const filteredProducts = products?.filter(product => {
        const filterValue = product?.name.toLowerCase();
        return filterValue.includes(keywords.toLowerCase());
      });
  
      setProducts(filteredProducts)
    }
   
  }


  useEffect(() => {
    filterSearch()
  }, [keywords])

  const getProducts = async() => {
    setLoading(true)
    const apiUrl = `${baseUrl}products`;
    try {
      const rawProductsResponse = await fetch(apiUrl);
    
      if (!rawProductsResponse.ok) {
        throw new Error('Network response was not ok');
      }
    
      // Parse the response body and store it in a variable
      const rawProductsData = await rawProductsResponse.json();
      console.log(rawProductsData);
      setProducts(rawProductsData)
    
      // Use 'products' in your code as needed
    } catch (error) {
      console.error('Error fetching data:', error);
    }

    setLoading(false)

  }

  useEffect(() => {
      getProducts()
  },[])

  const cartRefetch = () => {
    const cart = JSON.parse(localStorage.getItem("cartData"))
    setCartTotal(cart?.length)
  }

  useEffect(() => {
    cartRefetch()
  },[cartTrace])

  return (
    <>
      <Head>
        <title>Grocery App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


   <Layout cartTrace={cartTrace} setKeywords={setKeywords} keywords={keywords}>
    <ToastContainer />
    {/* this is home components  */}
      <HomeComponent products={products} cartTrace={cartTrace} setKeywords={setKeywords} keywords={keywords} setCarttrace={setCarttrace} loading={loading} />
   </Layout>

      
    </>
  )
}
